version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    environment:         
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - /var/projects/pos:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
      - ./backups:/backups
  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ismael14_16@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db